import type { NextPage } from "next";
import Head from "next/head";
import { getCollection } from "../lib/collection";
import styles from "../styles/Home.module.css";

const id: string =
  "http://localhost:3000/fixtures/iiif/collection/tenncities.json";

interface IIIFCollection {
  "@context": string | string[];
  id: string;
  type: "Collection";
  items: [];
}

interface Props {
  collection: IIIFCollection;
}

const Home: NextPage<Props> = ({ collection }) => {
  console.log(collection);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>What is Can?</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export async function getStaticProps() {
  const collection: any = await getCollection(id);

  return {
    props: { collection },
  };
}

export default Home;
